
services:
  habr-crawler:
    build:
      context: .
      dockerfile: habr-crawler/src/main/docker/Dockerfile
#    image: habr-crawler:latest
    container_name: habr-crawler
#    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
#      - ELASTICSEARCH_HOST=http://elasticsearch:9200
#      - ELASTICSEARCH_USERNAME=elastic
#      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
#    depends_on:
#      - elasticsearch
    networks:
      - habr-net
    env_file:
      - habr-crawler/src/main/.env.docker


  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    image: elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=pass

      #      - ELASTIC_PASSWORD=changeme  # Поменяйте на свой пароль
#      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - habr-net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - habr-crawler/src/main/.env.docker

  kibana:
    image: kibana:8.11.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_PUBLICBASEURL=http://localhost:5601
    networks:
      - habr-net
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # порт для приложений
      - "15672:15672"     # порт для UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - habr-net
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  es_data:
  rabbitmq_data:

networks:
  habr-net:
    driver: bridge
